---
name: ai_self_discover
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132267
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425908
milestone: '16.4'
type: development
group: group::ai framework
default_enabled: false
