---
name: bulk_import_idempotent_workers
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132702
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/426480
milestone: '16.5'
type: development
group: group::import and integrate
default_enabled: false
