---
name: custom_roles_ui_saas
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130089
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423077
milestone: '16.4'
type: development
group: group::authorization
default_enabled: true
