---
name: enforce_ssh_certificates
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132653
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/426235
milestone: '16.5'
type: development
group: group::source code
default_enabled: false
