---
name: jwt_auth_space_delimited_scopes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/133841
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427881
milestone: '16.5'
type: development
group: group::container registry
default_enabled: false
