---
name: mastodon_social_ui
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132892
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/428163
milestone: '16.5'
type: development
group: group::tenant scale
default_enabled: false
