---
name: project_tool_filter_with_scanner_name
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131310
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424509
milestone: '16.5'
type: development
group: group::threat insights
default_enabled: false
