---
name: restyle_login_page
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91673
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368387
milestone: '15.2'
type: development
group: group::authentication
default_enabled: true
